### ISSUE TITLE
Minimize pylint crash test case

### ISSUE THREAD

**Issue by sattlerc** [ChalmersGU-data-structure-courses/lab-system#61]
Pylint 3.3.3 on Python 3.13.1 crashes when running e.g. on [`course.py`](https://github.com/ChalmersGU-data-structure-courses/lab-system/blob/a17fab93664b18f14bc080461a73f864074072bb/course.py) (as done for #60):

```
Exception on node <FunctionDef.gitlab_netloc l.336 at 0x756edc71c3d0> in file '/home/noname/data-structures/lab-system-new/course.py'
Traceback (most recent call last):
  File "/home/noname/data-structures/lab-system-new/.venv/lib/python3.13/site-packages/pylint/utils/ast_walker.py", line 87, in walk
    callback(astroid)
    ~~~~~~~~^^^^^^^^^
  File "/home/noname/data-structures/lab-system-new/.venv/lib/python3.13/site-packages/pylint/checkers/classes/special_methods_checker.py", line 183, in visit_functiondef
    inferred = _safe_infer_call_result(node, node)
  File "/home/noname/data-structures/lab-system-new/.venv/lib/python3.13/site-packages/pylint/checkers/classes/special_methods_checker.py", line 42, in _safe_infer_call_result
    value = next(inferit)
  File "/home/noname/data-structures/lab-system-new/.venv/lib/python3.13/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 1658, in infer_call_result
    yield from returnnode.value.infer(context)
  File "/home/noname/data-structures/lab-system-new/.venv/lib/python3.13/site-packages/astroid/nodes/node_ng.py", line 168, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
                     ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noname/data-structures/lab-system-new/.venv/lib/python3.13/site-packages/astroid/decorators.py", line 86, in inner
    yield next(generator)
          ~~~~^^^^^^^^^^^
  File "/home/noname/data-structures/lab-system-new/.venv/lib/python3.13/site-packages/astroid/decorators.py", line 49, in wrapped
    for res in _func(node, context, **kwargs):
               ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noname/data-structures/lab-system-new/.venv/lib/python3.13/site-packages/astroid/nodes/node_classes.py", line 1769, in _infer
    yield from callee.infer_call_result(
        caller=self, context=callcontext
    )
  File "/home/noname/data-structures/lab-system-new/.venv/lib/python3.13/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2133, in infer_call_result
    if self.is_subtype_of("builtins.type", context) and len(caller.args) == 3:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noname/data-structures/lab-system-new/.venv/lib/python3.13/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2070, in is_subtype_of
    return any(anc.qname() == type_name for anc in self.ancestors(context=context))
  File "/home/noname/data-structures/lab-system-new/.venv/lib/python3.13/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2070, in <genexpr>
    return any(anc.qname() == type_name for anc in self.ancestors(context=context))
                                                   ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/noname/data-structures/lab-system-new/.venv/lib/python3.13/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 2245, in ancestors
    for baseobj in stmt.infer(context):
                   ~~~~~~~~~~^^^^^^^^^
  File "/home/noname/data-structures/lab-system-new/.venv/lib/python3.13/site-packages/astroid/nodes/node_ng.py", line 168, in infer
    for i, result in enumerate(self._infer(context=context, **kwargs)):
                     ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noname/data-structures/lab-system-new/.venv/lib/python3.13/site-packages/astroid/decorators.py", line 86, in inner
    yield next(generator)
          ~~~~^^^^^^^^^^^
  File "/home/noname/data-structures/lab-system-new/.venv/lib/python3.13/site-packages/astroid/decorators.py", line 49, in wrapped
    for res in _func(node, context, **kwargs):
               ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noname/data-structures/lab-system-new/.venv/lib/python3.13/site-packages/astroid/nodes/node_classes.py", line 585, in _infer
    frame, stmts = self.lookup(self.name)
                   ~~~~~~~~~~~^^^^^^^^^^^
  File "/home/noname/data-structures/lab-system-new/.venv/lib/python3.13/site-packages/astroid/nodes/_base_nodes.py", line 277, in lookup
    return self.scope().scope_lookup(self, name)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/noname/data-structures/lab-system-new/.venv/lib/python3.13/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 328, in scope_lookup
    return self._scope_lookup(node, name, offset)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/home/noname/data-structures/lab-system-new/.venv/lib/python3.13/site-packages/astroid/nodes/scoped_nodes/mixin.py", line 80, in _scope_lookup
    stmts = _filter_stmts(node, self.locals[name], self, offset)
  File "/home/noname/data-structures/lab-system-new/.venv/lib/python3.13/site-packages/astroid/filter_statements.py", line 90, in _filter_stmts
    if base_node.parent and base_node.statement() is myframe and myframe.parent:
                            ~~~~~~~~~~~~~~~~~~~^^
  File "/home/noname/data-structures/lab-system-new/.venv/lib/python3.13/site-packages/astroid/nodes/node_ng.py", line 295, in statement
    return self.parent.statement()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/noname/data-structures/lab-system-new/.venv/lib/python3.13/site-packages/astroid/nodes/scoped_nodes/scoped_nodes.py", line 413, in statement
    raise StatementMissing(target=self)
astroid.exceptions.StatementMissing: Statement not found on <Module.util.print_parse l.0 at 0x756ed97d37a0>
course.py:1:0: F0002: course.py: Fatal error while checking 'course.py'. Please open an issue in our bug tracker so we address this. (astroid-error)
```

We should minimize this test case and report it upstream.

**Comment by sattlerc** [comment]
The error message references the imported module `util.print_parse`. Running pylint on that one produces the same error. That's already a simplification.

**Comment by sattlerc** [comment]
Minimized test case:

```python
A = namedtuple("A", [])

def tuple():
    A()
```

**Comment by sattlerc** [comment]
Reported here: https://github.com/pylint-dev/pylint/issues/10159
